# Generated by Django 5.1.1 on 2024-10-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='employe specialization')),
            ],
        ),
        migrations.AddField(
            model_name='employeprofile',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='users', to='account.specialization', verbose_name='employe specializations'),
        ),
    ]
