repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
        exclude: ^.*\b(migrations)\b.*$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        files: \.py$
        exclude: ^.*\b(migrations)\b.*$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.11.2'
    hooks:
    -   id: mypy
        exclude: ^.*\b(migrations)\b.*$
        additional_dependencies:
          - django-stubs
          - mypy-extensions
          - django-environ
          - python-dotenv
          - djangorestframework-stubs[compatible-mypy]
          - djangorestframework
          - djangorestframework-simplejwt
          - django_extensions
          - psycopg2-binary
        args:
          - --config-file=pyproject.toml
          - --python-version=3.12
