services:
  django:
    build: .
    command: [ "python", "-m", "gunicorn", "patient_management.asgi:application", "--config", "contrib/gunicorn.conf.py", "--reload" ]
    hostname: patient-management-backend
    container_name: patient-management-django
    volumes:
      - .:/usr/src/django
    ports:
      - "8000:8000"
      - "5679:5679"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:16.2-alpine3.19
    container_name: patient-management-postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

volumes:
  dbdata: null
