# Generated by Django 5.1.1 on 2024-10-09 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_specialization_employeprofile_specializations'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaints', models.TextField(verbose_name='patient complaints')),
                ('prescription', models.TextField(verbose_name='doctor prescription')),
                ('report', models.TextField(verbose_name='doctor report')),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date which that instance has been created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time which that instance has been modified', verbose_name='updated at')),
                ('first_name', models.CharField(max_length=150, verbose_name='patient first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='patient last name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date which that instance has been created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time which that instance has been modified', verbose_name='updated at')),
                ('name', models.CharField(max_length=150, verbose_name='department name')),
                ('workers', models.ManyToManyField(blank=True, related_name='department', to='account.employeprofile', verbose_name='workers of department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=150, verbose_name='patient status')),
                ('profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='medical_screening.patientprofile', verbose_name='patient profile')),
            ],
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_closed', models.BooleanField(default=False, verbose_name='is screening closed')),
                ('opening_date', models.DateTimeField(auto_now_add=True, verbose_name='screning opening date')),
                ('closed_date', models.DateTimeField(null=True, verbose_name='screening closed date')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='screenings', to='medical_screening.patient', verbose_name='patient of screening')),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='description')),
                ('action_date', models.DateTimeField(auto_now=True, verbose_name='date of action')),
                ('status', models.CharField(max_length=50, verbose_name='screening step status')),
                ('forwarded_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.employeprofile', verbose_name='forwarded by')),
                ('forwarded_from', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comes_from', to='medical_screening.department', verbose_name='patient forwarded from')),
                ('forwarded_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fowarded_to', to='medical_screening.department', verbose_name='patitent forwaeded to')),
                ('last_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medical_screening.screeningsteps', verbose_name='last step')),
                ('medical_chart', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='medical_screening.medicalchart', verbose_name='medical chart')),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='steps', to='medical_screening.screening', verbose_name='step of screnning')),
            ],
        ),
        migrations.CreateModel(
            name='SickNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date which that instance has been created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time which that instance has been modified', verbose_name='updated at')),
                ('description', models.TextField(verbose_name='description of sick notes')),
                ('print_count', models.IntegerField(default=0, verbose_name='quantity of print')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.employeprofile', verbose_name='doctor who prescribe that sick note')),
                ('medical_chart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='medical_screening.medicalchart', verbose_name='medical chart')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='medical_screening.patient', verbose_name='patient of sicknote')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
